swagger: '2.0'
info:
  description: Api Documentation
  version: '1.0'
  title: Api Documentation
  termsOfService: 'urn:tos'
  contact: {}
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0'
host: 'mbsp01-devl-webapp.j22g6rr3zz.us-east-1.elasticbeanstalk.com'
basePath: /
tags:
  - name: product-pricing-controller
    description: Product Pricing Controller
paths:
  /fnmapi/mbsproductpricing:
    delete:
      tags:
        - product-pricing-controller
      summary: clearAllProductPricing
      operationId: clearAllProductPricingUsingDELETE
      consumes:
        - application/json
      produces:
        - application/json
        - application/vnd.fnma-v1+json
      parameters:
        - name: Accept
          in: header
          description: Accept
          required: true
          type: string
      responses:
        '200':
          description: OK
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
    post:
      tags:
        - product-pricing-controller
      summary: createProductPricing
      operationId: createProductPricingUsingPOST
      consumes:
        - application/json
      produces:
        - application/json
        - application/vnd.fnma-v1+json
      parameters:
        - in: body
          name: productPricingPORequest
          description: productPricingPORequest
          required: true
          schema:
            $ref: '#/definitions/ProductPricingPO'
        - name: Accept
          in: header
          description: Accept
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: object
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found

definitions:
   ProductId:
    type: object
    properties:
      identifier:
        type: integer
        format: int64
      sourceType:
        type: string
      type:
        type: string
   ProductPricingPO:
    type: object
    properties:
      buySellIndicator:
        type: string
      effectiveDate:
        type: string
        format: date-time
      marketTermType:
        type: string
        enum:
          - FN30
      passThroughRate:
        type: number
      productId:
        $ref: '#/definitions/ProductId'
      productNameCode:
        type: string
      settlementDate:
        type: string
        format: date-time