swagger: '2.0'
info:
  description: Api Documentation
  version: '1.0'
  title: Api Documentation
  termsOfService: 'urn:tos'
  contact: {}
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0'
host: 'mbsp01-devl-webapp.j22g6rr3zz.us-east-1.elasticbeanstalk.com'
basePath: /
tags:
  - name: product-controller
    description: Product Controller
paths:
  /fnmapi/mbsproducts:
    get:
      tags:
        - product-controller
      summary: getProducts
      operationId: getProductsUsingGET
      consumes:
        - application/json
      produces:
        - application/json
        - application/vnd.fnma-v1+json
      parameters:
        - name: Accept
          in: header
          description: Accept
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: "array"
            items:
              $ref: '#/definitions/ProductPO'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal server error
    post:
      tags:
        - product-controller
      summary: createProducts
      operationId: createProductsUsingPOST
      consumes:
        - application/json
        - application/vnd.fnma-v1+json
      produces:
        - application/json
        - application/vnd.fnma-v1+json
      parameters:
        - in: body
          name: productPO
          description: productPO
          required: true
          schema:
            $ref: '#/definitions/ProductPO'
        - name: Accept
          in: header
          description: Accept
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: object
        '201':
          description: Created
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal server error
    delete:
      tags:
        - product-controller
      summary: clearAllProducts
      operationId: clearAllProductsUsingDELETE
      consumes:
        - application/json
      produces:
        - application/json
        - application/vnd.fnma-v1+json
      parameters:
        - name: Accept
          in: header
          description: Accept
          required: true
          type: string
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal server error
definitions:
  ProductIdPO:
    type: object
    properties:
      identifier:
        type: integer
        format: int64
      sourceType:
        type: string
        enum:
          - PU
      type:
        type: string
        enum:
          - MBS
  ProductPO:
    type: object
    properties:
      agencyType:
        type: string
      description:
        type: string
      nameCode:
        type: string
      nameCodeSortOrder:
        type: integer
        format: int32
      productId:
        $ref: '#/definitions/ProductIdPO'
      securityTerm:
        type: integer
        format: int32