swagger: '2.0'
info:
  description: >-
    This is the MBS Automation portal where the lenders and traders login to
    submit, view, update the trade relation information
  version: '1.0'
  title: Swagger MBS Portal
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: mtascrum1@fanniemae.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0'
host: mbsp01-devl-webapp.j22g6rr3zz.us-east-1.elasticbeanstalk.com
basePath: /
tags:
  - name: transaction-history-controller
    description: Transaction History Controller
paths:
  '/fnmapi/transactionshistory':
    get:
      tags:
        - transaction-history-controller
      summary: getTransactionHistoryTrader
      operationId: getTransactionHistoryTraderUsingGET_1
      consumes:
        - application/json
      produces:
        - application/json
        - application/vnd.fnma-v1+json
      parameters:
        - name: Accept
          in: header
          description: Accept
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: "array"
            items:
              $ref: "#/definitions/TransactionHistoryPO"
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal server error
definitions:
  ProductIdPO:
    type: object
    properties:
      identifier:
        type: integer
        format: int64
      sourceType:
        type: string
        enum:
          - PU
      type:
        type: string
        enum:
          - MBS
  ProductPO:
    type: object
    properties:
      agencyType:
        type: string
      description:
        type: string
      nameCode:
        type: string
      nameCodeSortOrder:
        type: integer
        format: int32
      productId:
        $ref: '#/definitions/ProductIdPO'
      securityTerm:
        type: integer
        format: int32
  TransactionHistoryPO:
    type: object
    properties:
      acceptanceDate:
        type: string
        example: 2001-07-04T12:08:56.235-0700
      lenderName:
        type: string
      pricePercent:
        type: string
      pricePercentHandleText:
        type: string
      pricePercentTicksText:
        type: string
      product:
        $ref: '#/definitions/ProductPO'
      stateType:
        type: string
        enum:
          - LENDER_OPEN
          - TRADER_PRICED
          - TRADER_PASSED
          - LENDER_ACCEPTED
          - LENDER_REJECTED
          - TRADER_CONFIRMED
          - TRADER_REJECTED
          - PENDING_EXECUTION
          - EXECUTED
          - LENDER_TIMEOUT
          - TRADER_TIMEOUT
          - ERROR
      submissionDate:
        type: string
        example: 2001-07-04T12:08:56.235-0700
      tradeAmount:
        type: string
      tradeBuySellType:
        type: string
      tradeCouponRate:
        type: string
      tradeSettlementDate:
        type: string
        example: 2001-07-04
      tradeSrcId:
        type: string
      tradeSrcPrimaryId:
        type: integer
        format: int64
      tradeSubPortfolioId:
        type: integer
        format: int64
      traderName:
        type: string
      transReqId:
        type: string
      tradeDate:
        type: string
        example: 2001-07-04
      lenderEntityName:
        type: string